allowed_workspaces: []

allowed_commands:
  xcodebuild:
    binary_path: /usr/bin/xcodebuild
    allowed_args_regex: ^(-version|-showsdks|-list.*)$
    require_interactive_approval: false
  simulator:
    binary_path: /usr/bin/open
    allowed_args_regex: ^-a Simulator$
    require_interactive_approval: false
  git-credential-osxkeychain:
    binary_path: /usr/bin/git
    allowed_args_regex: ^credential-osxkeychain (get|store|erase)$
    require_interactive_approval: true
  sw_vers:
    binary_path: /usr/bin/sw_vers
    allowed_args_regex: ^.*$
    require_interactive_approval: false
